name: Lint markdown files

on:
  schedule:
    # UTC Time, At 15:00 on day-of-month 15.
    - cron: "0 15 15 * *"
  workflow_dispatch:
  repository_dispatch:
  pull_request:
    branches:
      - master

jobs:
# Ref: https://github.com/igorshubovych/markdownlint-cli
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint markdown files (with Docker)
      run: |
        docker run -v $PWD:/workdir ghcr.io/igorshubovych/markdownlint-cli:latest "*.md"
